### ISSUE TITLE
Update cpu, memory, io hog to arcaflow scenarios

### ISSUE THREAD

**Issue by paigerube14** [redhat-chaos/krkn-hub#87]
After PR: https://github.com/redhat-chaos/krkn/pull/395 gets merged we will need to update the pointers of the cpu, memory and io hog to the new scenarios and add the new parameters for this 

Will want to take out any refernces to litmus

**Comment by chaitanyaenr** [comment]
@tsebastiani added the changes. Closing the issue. Thanks.
